-- Tabella per le configurazioni dei canali temporanei
CREATE TABLE TEMP_CHANNEL (
    ID BIGINT PRIMARY KEY,              -- Modificato da INT a BIGINT
    ID_CH1 VARCHAR(255) NULL,
    ID_CH2 VARCHAR(255) NULL
);

-- Tabella per le configurazioni degli eventi/festività (Hollyday)
CREATE TABLE HOLLYDAY (
    ID BIGINT PRIMARY KEY,              -- Modificato da INT a BIGINT
    ID_CH_1 VARCHAR(255) NULL,
    ID_CH_2 VARCHAR(255) NULL
);

-- Tabella per le Gilde (Server)
CREATE TABLE GUILD (
    ID BIGINT PRIMARY KEY,              -- Modificato da INT a BIGINT
    NOME VARCHAR(255) NOT NULL,
    TEMPCHANNEL_ID BIGINT NULL,        -- Modificato da INT a BIGINT
    HOLLYDAY_ID BIGINT NULL,           -- Modificato da INT a BIGINT
    WELCOME_ID VARCHAR(255) NULL,
    LOG_ID VARCHAR(255) NULL,

    FOREIGN KEY (TEMPCHANNEL_ID) REFERENCES TEMP_CHANNEL(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (HOLLYDAY_ID) REFERENCES HOLLYDAY(ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Tabella per i Ruoli
CREATE TABLE ROLE (
    ID BIGINT PRIMARY KEY,              -- Modificato da INT a BIGINT
    NOME VARCHAR(255) NOT NULL,
    COLORE VARCHAR(50) NULL,
    IDGUILD BIGINT NOT NULL,            -- Modificato da INT a BIGINT

    FOREIGN KEY (IDGUILD) REFERENCES GUILD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tabella per i Membri (Utenti Globali)
CREATE TABLE MEMBER (
    ID VARCHAR(255) PRIMARY KEY,       -- Questo rimane VARCHAR, adatto per ID come quelli di Discord
    NOME VARCHAR(255) NOT NULL
);

-- Tabella di Giunzione per Gilde e Membri (relazione Molti-a-Molti)
CREATE TABLE GUILD_MEMBER (
    GUILD_ID BIGINT NOT NULL,          -- Modificato da INT a BIGINT
    MEMBER_ID VARCHAR(255) NOT NULL,   -- Fa riferimento a MEMBER.ID che è VARCHAR
    PRIMARY KEY (GUILD_ID, MEMBER_ID),

    FOREIGN KEY (GUILD_ID) REFERENCES GUILD(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tabella di Giunzione per Membri e Ruoli (relazione Molti-a-Molti)
CREATE TABLE MEMBER_ROLE (
    MEMBER_ID VARCHAR(255) NOT NULL,   -- Fa riferimento a MEMBER.ID che è VARCHAR
    ROLE_ID BIGINT NOT NULL,           -- Modificato da INT a BIGINT
    PRIMARY KEY (MEMBER_ID, ROLE_ID),

    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tabella per i Log
CREATE TABLE LOG (
    ID BIGINT PRIMARY KEY,              -- Modificato da INT a BIGINT
    TYPE VARCHAR(100) NOT NULL,
    DESCRIZIONE TEXT NULL,
    ID_GUILD BIGINT NOT NULL,           -- Modificato da INT a BIGINT

    FOREIGN KEY (ID_GUILD) REFERENCES GUILD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);