CREATE TABLE
    TEMP_CHANNEL (
        ID VARCHAR(255) PRIMARY KEY,
        CATEGORY_CH VARCHAR(255) NULL,
        DUO_CH VARCHAR(255) NULL,
        TRIO_CH VARCHAR(255) NULL,
        QUARTET_CH VARCHAR(255) NULL,
        NOLIMIT_CH VARCHAR(255) NULL
    );

CREATE TABLE
    HOLYDAY (
        ID VARCHAR(255) PRIMARY KEY,
        CATEGORY_CH VARCHAR(255) NULL,
        NAME_CHANNEL VARCHAR(255) NULL,
        HOLYDAY_CHANNEL VARCHAR(255) NULL
    );

CREATE TABLE
    GUILD (
        ID VARCHAR(255) PRIMARY KEY,
        NOME VARCHAR(255) NOT NULL,
        TEMPCHANNEL_ID VARCHAR(255) NULL,
        HOLYDAY_ID VARCHAR(255) NULL,
        WELCOME_ID VARCHAR(255) NULL,
        LOG_ID VARCHAR(255) NULL,
        FOREIGN KEY (TEMPCHANNEL_ID) REFERENCES TEMP_CHANNEL (ID) ON DELETE SET NULL ON UPDATE CASCADE,
        FOREIGN KEY (HOLYDAY_ID) REFERENCES HOLYDAY (ID) ON DELETE SET NULL ON UPDATE CASCADE
    );

CREATE TABLE
    ROLE (
        ID VARCHAR(255) PRIMARY KEY,
        NOME VARCHAR(255) NOT NULL,
        COLORE VARCHAR(50) NULL,
        IDGUILD VARCHAR(255) NOT NULL,
        FOREIGN KEY (IDGUILD) REFERENCES GUILD (ID) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    MEMBER (
        ID VARCHAR(255) PRIMARY KEY,
        NOME VARCHAR(255) NOT NULL
    );

CREATE TABLE
    GUILD_MEMBER (
        GUILD_ID VARCHAR(255) NOT NULL,
        MEMBER_ID VARCHAR(255) NOT NULL,
        PRIMARY KEY (GUILD_ID, MEMBER_ID),
        FOREIGN KEY (GUILD_ID) REFERENCES GUILD (ID) ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    MEMBER_ROLE (
        MEMBER_ID VARCHAR(255) NOT NULL,
        ROLE_ID VARCHAR(255) NOT NULL,
        PRIMARY KEY (MEMBER_ID, ROLE_ID),
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    LOG (
        ID VARCHAR(255) PRIMARY KEY,
        TYPE VARCHAR(100) NOT NULL,
        DESCRIZIONE TEXT NULL,
        ID_GUILD VARCHAR(255) NOT NULL,
        FOREIGN KEY (ID_GUILD) REFERENCES GUILD (ID) ON DELETE CASCADE ON UPDATE CASCADE
    );