CREATE TABLE MEMBER(
    ID VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);


CREATE TABLE GUILD(
    ID VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    WELCOME_ID VARCHAR(255) NULL,
    LOG_ID VARCHAR(255) NULL,
    ROLEDEFAULT_ID VARCHAR(255) NULL,
    ROLEBOTDEFAULT_ID VARCHAR(255) NULL
);

CREATE TABLE TEMP_CHANNEL(
    GUILD_ID VARCHAR(255) PRIMARY KEY,
    CATEGORY_CH VARCHAR(255) NULL,
    DUO_CH VARCHAR(255) NULL,
    TRIO_CH VARCHAR(255) NULL,
    QUARTET_CH VARCHAR(255) NULL,
    NOLIMIT_CH VARCHAR(255) NULL,
    FOREIGN KEY(GUILD_ID) REFERENCES GUILD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HOLYDAY(
    GUILD_ID VARCHAR(255) PRIMARY KEY,
    CATEGORY_CH VARCHAR(255) NULL,
    NAME_CHANNEL VARCHAR(255) NULL,
    HOLYDAY_CHANNEL VARCHAR(255) NULL,
    FOREIGN KEY(GUILD_ID) REFERENCES GUILD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ROLE(
    ID VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    COLORE VARCHAR(50) NULL,
    IDGUILD VARCHAR(255) NOT NULL,
    FOREIGN KEY(IDGUILD) REFERENCES GUILD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE GUILD_MEMBER(
    GUILD_ID VARCHAR(255) NOT NULL,
    MEMBER_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY(GUILD_ID, MEMBER_ID),
    FOREIGN KEY(GUILD_ID) REFERENCES GUILD(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE MEMBER_ROLE(
    MEMBER_ID VARCHAR(255) NOT NULL,
    ROLE_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY(MEMBER_ID, ROLE_ID),
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LOGS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    GUILD_ID VARCHAR(25) NOT NULL,
    LOG_TYPE VARCHAR(50) NOT NULL,
    ACTOR_ID VARCHAR(25) NULL,
    TARGET_ID VARCHAR(25) NULL,
    TARGET_TYPE VARCHAR(20) NULL,
    DETAILS JSON NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    INDEX idx_guild_type(GUILD_ID, LOG_TYPE),
    INDEX idx_actor_id(ACTOR_ID),
    INDEX idx_target_id(TARGET_ID),
    FOREIGN KEY(GUILD_ID) REFERENCES GUILD(ID) ON DELETE CASCADE
);
