name: Node.js CI

on:
  push:
    branches: [ "host" ]

jobs:
  build:
    runs-on: self-hosted
    env:
      TOKEN: ${{ secrets.TOKEN }}
      GITTOKEN: ${{ secrets.GITTOKEN }}
    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Node.js application
      run: node index.js

    - name: Complete task
      run: echo "Task completed successfully."

